project:
  type: website

website:
  title: "Quarto Basic"
  page-navigation: true  

  sidebar:
    style: "floating"
    border: true
    align: center
    contents:
      - index.qmd
      - section: "Basics"
        href: basics/basics.qmd
        contents:
          - basics/basics.qmd
      - section: "Workflow"
        href: workflow/workflow.qmd
        contents:
          - workflow/workflow.qmd
          - workflow/data-science-workflow.qmd
      - section: "Examples"
        href: examples/intro.ipynb
        contents: "examples/*.ipynb"
      - references.qmd
    tools:
      - icon: github
        href: https://github.com/green-nk/quarto-basic
        text: Source code
  search:
    type: textbox
    show-item-context: tree

  page-footer: 
    border: true
    left: |
      Copyright &copy; 2024, Nakarin Korsuwan\
      Made with [Quarto](https://quarto.org/)
    right: 
      - icon: github
        href: https://github.com/green-nk/quarto-basic

format:
  html:
    toc: true
    code-fold: false
    theme:
      light: flatly
      dark: darkly

execute:
  freeze: auto
